<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Barat_next</name>
   <tag></tag>
   <elementGuidId>9bc9379a-07a6-48ed-a700-8b8dcfc74bc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='controls']/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3bbe00a-00a3-4e45-8ac9-0a84a81173ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>d9bb910a-c434-49fb-b87b-5283eb03f98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>history</value>
      <webElementGuid>a5635edd-56e4-41f3-ae6b-1300b69fdc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#2</value>
      <webElementGuid>a682f438-14b6-4c85-9723-7a6dc7c0e212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;controls&quot;)/div[@class=&quot;nav-controls&quot;]/a[@class=&quot;next&quot;]</value>
      <webElementGuid>69b72805-e9cb-4f91-8ddf-4f5a93363872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controls']/div/a[2]</value>
      <webElementGuid>84f0df50-b32a-4cd6-addc-be837c1a2478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#2')])[3]</value>
      <webElementGuid>a52dd8f2-39bf-40c7-9e99-cf137df3663e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]</value>
      <webElementGuid>4e6ffb88-3fbd-4a62-905b-23ed5601658d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#2']</value>
      <webElementGuid>0db2d423-4edb-405c-8749-af86f02b53f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
