<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Barat_next_1</name>
   <tag></tag>
   <elementGuidId>af849ad5-d9c4-4169-bee6-595e69a857c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='controls']/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14386a4e-8ae9-4185-a0d3-f23e4616c77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>0b23c013-c631-41b2-abde-489f90adb658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>history</value>
      <webElementGuid>b5d54908-ed70-4e89-aebe-b49a2e707ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#3</value>
      <webElementGuid>aeaefcc8-1d8e-4f3b-81d9-5da641b1196a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;controls&quot;)/div[@class=&quot;nav-controls&quot;]/a[@class=&quot;next&quot;]</value>
      <webElementGuid>e27d75b7-c3ec-40d4-a9e1-c75c5b74dc99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controls']/div/a[2]</value>
      <webElementGuid>c900bbbb-5eea-408b-a4ad-a30a8a900ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#3')])[2]</value>
      <webElementGuid>bdb93957-b832-4f81-b32b-0bd658a67d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]</value>
      <webElementGuid>14dc2d48-d9de-4e87-9cbc-be715fcfdb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#3']</value>
      <webElementGuid>7b30a440-5c3c-4ad4-89a2-926b22315fb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
