<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Instagramable</name>
   <tag></tag>
   <elementGuidId>e830ed92-5bff-4398-adcc-4f91fc85b643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(10) > div.col-sm-6.col-md-12 > a > div.list-group-item.minified</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='restaurant-theme']/li[10]/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2a1c2f8-ef74-47ae-b7e6-fbc60facfec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item minified</value>
      <webElementGuid>9ada4a20-7ab5-4507-9c9c-94db6a481033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instagramable</value>
      <webElementGuid>d709701a-6953-4e5f-8024-6153dcaf04ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-restaurant-theme&quot;)/div[@class=&quot;list-restaurant-theme&quot;]/ul[@id=&quot;restaurant-theme&quot;]/li[10]/div[@class=&quot;col-sm-6 col-md-12&quot;]/a[1]/div[@class=&quot;list-group-item minified&quot;]</value>
      <webElementGuid>05e5591b-8728-4b1d-a0b5-1d641900affc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='restaurant-theme']/li[10]/div/a/div</value>
      <webElementGuid>317a257a-a460-42ae-a3d4-025eb1a21d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Babi Enak'])[1]/following::div[2]</value>
      <webElementGuid>0ecd2332-6e13-45d6-a04b-1ea036791d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legendaris'])[1]/following::div[4]</value>
      <webElementGuid>28571841-02ac-4f08-917f-4ce406a39453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Makanan Lucu'])[1]/preceding::div[1]</value>
      <webElementGuid>b5d1ab31-a191-4e22-b8d2-40e45a09b864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cemilan'])[1]/preceding::div[3]</value>
      <webElementGuid>b7846db7-4fab-4adf-8d53-cc79b4c11a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Instagramable']/parent::*</value>
      <webElementGuid>c68f10b1-4105-42ad-93d8-4fe738949400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/div/a/div</value>
      <webElementGuid>637e7045-06a2-41e4-afcc-5af4a966b362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Instagramable' or . = 'Instagramable')]</value>
      <webElementGuid>8a2f1ef1-01e7-465a-a31e-4dcfa0beb64e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
