<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Instagramable</name>
   <tag></tag>
   <elementGuidId>b8ec70ae-b186-4d30-b0be-461165ee104b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.list-group-item.header-theme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum dapat email konfirmasi?'])[1]/following::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5c3ed344-ae09-4475-b2c4-d31db2ff46b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item header-theme</value>
      <webElementGuid>e9882147-9b40-4c0e-a11a-243e38a083e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instagramable</value>
      <webElementGuid>4f4ae0d0-b607-4a89-b773-80fb1468f12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js no-touch csstransforms3d csstransitions win chrome chrome121 webkit webkit537&quot;]/body[1]/div[@class=&quot;main-wrap&quot;]/main[1]/div[@class=&quot;middle-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;wrapper themes&quot;]/h1[@class=&quot;list-group-item header-theme&quot;]</value>
      <webElementGuid>bbc806a2-5fdb-4c65-9347-a94d748e3e66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum dapat email konfirmasi?'])[1]/following::h1[1]</value>
      <webElementGuid>fb48b8e6-a4ae-40ac-a573-df7aa1edfa05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cork&amp;Screw Country Club'])[1]/preceding::h1[1]</value>
      <webElementGuid>56a17083-dead-45b6-8bf7-ee2ba92f54e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bali Vibes in Jakarta'])[1]/preceding::h1[1]</value>
      <webElementGuid>0d379ec6-32f2-4c8c-85b8-50398809d4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Instagramable']/parent::*</value>
      <webElementGuid>3e403f6e-9dd1-4bcd-8497-1764a5024fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>2d80cb23-f0e6-4460-9aad-9b15ac9bab95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Instagramable' or . = 'Instagramable')]</value>
      <webElementGuid>37b29d97-88d5-4d9b-b68e-8ec229533f5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
