<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>2bb2676d-77f4-4e59-bb4a-cbaaf6a513ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;menu-cork-screw-country-club-senayan-1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//figure[@id='slideshow']/span/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4ac1df13-2711-4250-ab9e-cd5435319095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>menu-cork-screw-country-club-senayan-1</value>
      <webElementGuid>8f2f51db-57dc-4720-a166-589dc2abd180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-pergikuliner.com/RbuKm9SeNpUsk8p8w1b5nlNB0w8=/945x0/smart/filters:watermark(https://assets-pergikuliner.com/assets/pegimakan-logo-3e147c56e232f471596371920946ae65.png,-0,-3,10):no_upscale()/https://assets-pergikuliner.com/uploads/image/picture/3167835/picture-1705934606.jpg</value>
      <webElementGuid>4fcaa593-d993-4145-ab67-dff1a4a5e035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slideshow&quot;)/span[@class=&quot;image-wrapper current&quot;]/div[1]/a[@class=&quot;advance-link&quot;]/img[1]</value>
      <webElementGuid>6c593e17-508d-43c8-a134-a0c4bfa7f350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='slideshow']/span/div/a/img</value>
      <webElementGuid>ea89bc82-d67b-45e7-a2f4-a1663265a140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='menu-cork-screw-country-club-senayan-1']</value>
      <webElementGuid>aab07baf-ab85-4011-b036-c6492a014db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a/img</value>
      <webElementGuid>92d238f7-81cc-4c33-ba79-e3fd9bbc0fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'menu-cork-screw-country-club-senayan-1' and @src = 'https://assets-pergikuliner.com/RbuKm9SeNpUsk8p8w1b5nlNB0w8=/945x0/smart/filters:watermark(https://assets-pergikuliner.com/assets/pegimakan-logo-3e147c56e232f471596371920946ae65.png,-0,-3,10):no_upscale()/https://assets-pergikuliner.com/uploads/image/picture/3167835/picture-1705934606.jpg']</value>
      <webElementGuid>6979b2d6-1087-4601-a1e5-bef2009cfc3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
