<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3b875d6b-acb7-4f18-82f5-32bc93abacba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;foto-cork-screw-country-club&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//figure[@id='slideshow']/span/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>250b2f84-03a0-4a97-9496-9a4d1b7ea0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>foto-cork-screw-country-club</value>
      <webElementGuid>053b8105-f222-429f-9a4d-fc013cbba007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-pergikuliner.com/2BV5vCTmgRzMEK1fDXhg0cLy4q0=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2682549/picture-1666348634.jpg</value>
      <webElementGuid>273ad580-165f-4ec1-b103-3d7cb6cb725b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://assets-pergikuliner.com/2BV5vCTmgRzMEK1fDXhg0cLy4q0=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2682549/picture-1666348634.jpg 1x, https://assets-pergikuliner.com/wi9VfgA1BtSY_akbXVHdpxwnwog=/770x580/smart/filters:no_upscale()/https://assets-pergikuliner.com/uploads/image/picture/2682549/picture-1666348634.jpg 2x</value>
      <webElementGuid>de649d2c-39b6-45ba-bb78-b2ba91451a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>385</value>
      <webElementGuid>527a1745-13ca-4104-81f2-49f9be02c98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>290</value>
      <webElementGuid>45aa44a9-1c97-4d6a-80c8-a20bf0f4ef20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slideshow&quot;)/span[@class=&quot;image-wrapper current&quot;]/div[1]/a[@class=&quot;advance-link&quot;]/img[1]</value>
      <webElementGuid>38c3008b-329a-4dc6-98a2-2403c18def56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='slideshow']/span/div/a/img</value>
      <webElementGuid>d725a996-cf08-412d-9f15-53ac12c806ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='foto-cork-screw-country-club']</value>
      <webElementGuid>f8d27bbf-8293-4f19-bbef-33dcafa0426c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>df2cdef2-c116-4360-b5c7-9b5f21457d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'foto-cork-screw-country-club' and @src = 'https://assets-pergikuliner.com/2BV5vCTmgRzMEK1fDXhg0cLy4q0=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2682549/picture-1666348634.jpg']</value>
      <webElementGuid>9e946ca9-dfc7-424d-949f-65a32b7a4ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
