<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>079cb493-a52c-4e1c-b5a4-9d51e862e763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;foto-cork-screw-country-club&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//figure[@id='slideshow']/span/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>45a994c5-852c-4d56-9798-e11469e5c290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>foto-cork-screw-country-club</value>
      <webElementGuid>0095a637-bfb7-462c-92b2-edde994ecd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-pergikuliner.com/Tn_N8j2nTX0N6gXKgBwfc4o8170=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2682550/picture-1666348634.jpg</value>
      <webElementGuid>46529ebe-689c-4fe1-b8b2-0ffdb24ab263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://assets-pergikuliner.com/Tn_N8j2nTX0N6gXKgBwfc4o8170=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2682550/picture-1666348634.jpg 1x, https://assets-pergikuliner.com/JkixFiSzA4PJEpn3u5qJ5n7A91E=/770x580/smart/filters:no_upscale()/https://assets-pergikuliner.com/uploads/image/picture/2682550/picture-1666348634.jpg 2x</value>
      <webElementGuid>3b1be96d-c0db-43ed-8f22-025de198e84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>385</value>
      <webElementGuid>c632bd67-3f64-43c6-bf14-d82b9ac9bca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>290</value>
      <webElementGuid>42bd2580-eea1-4148-91ca-bd79b61eac1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slideshow&quot;)/span[@class=&quot;image-wrapper current&quot;]/div[1]/a[@class=&quot;advance-link&quot;]/img[1]</value>
      <webElementGuid>fdf95f17-f745-462c-80a3-67a629bfe3fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='slideshow']/span/div/a/img</value>
      <webElementGuid>ca9a70e2-c5a0-4fbf-a41a-d4d4502046c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='foto-cork-screw-country-club']</value>
      <webElementGuid>afd77393-12ac-4e7f-b0c0-99938a0a75a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>6bff633c-4d8d-4947-9b85-c1cdfea8f7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'foto-cork-screw-country-club' and @src = 'https://assets-pergikuliner.com/Tn_N8j2nTX0N6gXKgBwfc4o8170=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2682550/picture-1666348634.jpg']</value>
      <webElementGuid>b31ab11b-f010-485b-b766-969962c027fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
