<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>72304ee8-5660-4e06-aef3-d5091e247041</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;foto-cork-screw-country-club&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//figure[@id='slideshow']/span/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f54b371a-d205-4c4b-b7e3-3aaa49dee25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>foto-cork-screw-country-club</value>
      <webElementGuid>6cf595a2-c898-4df5-a4f5-0522b9b78e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-pergikuliner.com/r9PaGbN0qXhq8CnnvbzRe_B2RkI=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2682551/picture-1666348634.jpg</value>
      <webElementGuid>14d1d8ca-3c82-4d20-b428-d69908ef4184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://assets-pergikuliner.com/r9PaGbN0qXhq8CnnvbzRe_B2RkI=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2682551/picture-1666348634.jpg 1x, https://assets-pergikuliner.com/cIQBcPFJFY_ZXm22eSn64sM8Irk=/770x580/smart/filters:no_upscale()/https://assets-pergikuliner.com/uploads/image/picture/2682551/picture-1666348634.jpg 2x</value>
      <webElementGuid>25d11a54-ee3a-416a-bcd6-2c37afbbe3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>385</value>
      <webElementGuid>03e0dd8b-26ad-49db-bf24-c5d070ad8489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>290</value>
      <webElementGuid>15903b3a-3762-4bf8-9825-921d8a2867fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slideshow&quot;)/span[@class=&quot;image-wrapper current&quot;]/div[1]/a[@class=&quot;advance-link&quot;]/img[1]</value>
      <webElementGuid>d04c2478-00a0-478e-9989-1a9174e5b827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='slideshow']/span/div/a/img</value>
      <webElementGuid>61241a3d-877b-40df-a8f7-d464af995894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='foto-cork-screw-country-club']</value>
      <webElementGuid>7bd5d9e6-4f1c-45d0-b90f-6663a0430398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>8f6a1db8-32e9-4277-8afd-d0a894824647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'foto-cork-screw-country-club' and @src = 'https://assets-pergikuliner.com/r9PaGbN0qXhq8CnnvbzRe_B2RkI=/385x290/smart/https://assets-pergikuliner.com/uploads/image/picture/2682551/picture-1666348634.jpg']</value>
      <webElementGuid>fa3977ee-248f-4407-9543-eb3be1daecfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
