<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1 (1)</name>
   <tag></tag>
   <elementGuidId>b6d66a12-c0bb-472b-a2ae-d520d2bbb7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;menu-cork-screw-country-club-senayan-2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//figure[@id='slideshow']/span/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f92652fa-f5ed-4b9e-a94e-51f846ef0ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>menu-cork-screw-country-club-senayan-2</value>
      <webElementGuid>e1ea5375-d4fc-4782-82a4-971e598e9b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-pergikuliner.com/3l9py1SdP7GmWROwGLkeci-g9aQ=/945x0/smart/filters:watermark(https://assets-pergikuliner.com/assets/pegimakan-logo-3e147c56e232f471596371920946ae65.png,-0,-3,10):no_upscale()/https://assets-pergikuliner.com/uploads/image/picture/3167836/picture-1705934609.jpg</value>
      <webElementGuid>c1603ccb-03a3-4be4-9e8a-84e91a7dd537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slideshow&quot;)/span[@class=&quot;image-wrapper current&quot;]/div[1]/a[@class=&quot;advance-link&quot;]/img[1]</value>
      <webElementGuid>e9dc121e-2790-44dc-98cd-25fb58b3e776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='slideshow']/span/div/a/img</value>
      <webElementGuid>11c03cc4-27e4-4e4d-b3d4-631261ab412c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='menu-cork-screw-country-club-senayan-2']</value>
      <webElementGuid>0cf1d205-436c-4735-903b-65c180b1be29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a/img</value>
      <webElementGuid>1e5e7cea-0a3b-49d6-901d-52e71270c117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'menu-cork-screw-country-club-senayan-2' and @src = 'https://assets-pergikuliner.com/3l9py1SdP7GmWROwGLkeci-g9aQ=/945x0/smart/filters:watermark(https://assets-pergikuliner.com/assets/pegimakan-logo-3e147c56e232f471596371920946ae65.png,-0,-3,10):no_upscale()/https://assets-pergikuliner.com/uploads/image/picture/3167836/picture-1705934609.jpg']</value>
      <webElementGuid>0ecf568f-c715-44e7-9d9c-9bc9ef1a16da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
