<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2 (1)</name>
   <tag></tag>
   <elementGuidId>26d2c43f-97a2-427c-a348-8c73e68ab441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;menu-cork-screw-country-club-senayan-3&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//figure[@id='slideshow']/span/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>080ac006-ff8a-4c4a-8afb-7f679554ff50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>menu-cork-screw-country-club-senayan-3</value>
      <webElementGuid>8f2745b3-b0ab-45f7-bc36-d145b2172899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets-pergikuliner.com/CXJT7LIiOiWfPNYq13YXaZzddGA=/945x0/smart/filters:watermark(https://assets-pergikuliner.com/assets/pegimakan-logo-3e147c56e232f471596371920946ae65.png,-0,-3,10):no_upscale()/https://assets-pergikuliner.com/uploads/image/picture/3167837/picture-1705934610.jpg</value>
      <webElementGuid>fcdaf764-7658-41b4-a4dc-0cb9edef4cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slideshow&quot;)/span[@class=&quot;image-wrapper current&quot;]/div[1]/a[@class=&quot;advance-link&quot;]/img[1]</value>
      <webElementGuid>bf591f79-949a-4678-b437-e6d03f21a4a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='slideshow']/span/div/a/img</value>
      <webElementGuid>f0dc01e8-4ccb-4371-b4f8-8d141ba77b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='menu-cork-screw-country-club-senayan-3']</value>
      <webElementGuid>baef1aeb-668b-419e-bef7-23c26324aa28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a/img</value>
      <webElementGuid>3a83c975-f7dd-40fc-8bda-d080e48abcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'menu-cork-screw-country-club-senayan-3' and @src = 'https://assets-pergikuliner.com/CXJT7LIiOiWfPNYq13YXaZzddGA=/945x0/smart/filters:watermark(https://assets-pergikuliner.com/assets/pegimakan-logo-3e147c56e232f471596371920946ae65.png,-0,-3,10):no_upscale()/https://assets-pergikuliner.com/uploads/image/picture/3167837/picture-1705934610.jpg']</value>
      <webElementGuid>8368d3d2-fe27-4ef1-a6d8-86a5964b152a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
