<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>9c76b922-cad2-4c81-91d8-a5ef936fbb0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-nav-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='login-nav-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90ed4288-6c38-412a-b481-668cc4a30fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1c190395-6d7d-42fb-9c99-0364acc07f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>20341e7d-dd47-4224-9261-0f6312b29ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#signinModal</value>
      <webElementGuid>54fb5886-363a-4115-942f-2b69f36c6cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-nav-btn</value>
      <webElementGuid>7eeda60e-03ae-4286-9f26-a50fcc19a706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signing</value>
      <webElementGuid>d5b55b95-deda-4c65-928d-8ee9e17e890d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>cb0bbbb3-0a83-441b-aa7c-52e74f95ff87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-nav-btn&quot;)</value>
      <webElementGuid>47032f00-fffd-41f5-a927-83a922b702a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='login-nav-btn']</value>
      <webElementGuid>d444811d-12ae-4c30-9501-5b7dde14e207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-example-navbar-collapse-1']/ul[2]/li[2]/a</value>
      <webElementGuid>a1977c65-5dd3-4002-bdc4-a22c896352ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Login')])[2]</value>
      <webElementGuid>525de790-a744-4405-8cdf-619fb5511461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terserah aja deh!'])[2]/following::a[1]</value>
      <webElementGuid>9134beb0-1150-4960-9bb5-e6a27747f98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PergiKuliner'])[1]/following::a[2]</value>
      <webElementGuid>e7ac593f-e8b2-4a5e-a491-eaebccfa94c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/preceding::a[2]</value>
      <webElementGuid>e2a02e13-366b-4606-a02d-5bcd201a1ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa password?'])[1]/preceding::a[2]</value>
      <webElementGuid>2ce02b4b-843e-4c1e-b57a-e21e43e87d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>3cac436c-7603-4441-aed3-f22787ecd337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/a</value>
      <webElementGuid>948ef07b-a5ac-4547-b8ce-0e6f0b96ded3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'login-nav-btn' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>22d6e35c-4a4b-4924-909b-e298269d3874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
