<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PergiKuliner</name>
   <tag></tag>
   <elementGuidId>97ae26a0-35b5-470b-b79a-3f454acd45ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.navbar-brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerweb']/div/nav/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed789c50-4dce-415c-aeda-3ffe19adb480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand</value>
      <webElementGuid>e40a9094-3cd8-4025-86d0-0eaa6b2ba913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PergiKuliner Home</value>
      <webElementGuid>3da6cfc2-18ce-4199-8f73-3576637e2e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>fe6ec33c-49cc-46de-9d7e-df3affc34f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PergiKuliner</value>
      <webElementGuid>4f438c03-1975-4d79-8494-34c15c4bab09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerweb&quot;)/div[@class=&quot;wrapper new-home&quot;]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;navbar-header&quot;]/div[@class=&quot;sm-scr-center-adj&quot;]/a[@class=&quot;navbar-brand&quot;]</value>
      <webElementGuid>9d3146c0-6ecc-4a3e-a5fe-bc4e0d581258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerweb']/div/nav/div/div/div/a</value>
      <webElementGuid>1da59927-fe0d-4060-8fb6-a2013c7d431e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PergiKuliner')]</value>
      <webElementGuid>785ed720-f0f6-491b-968d-746ecefc66bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© copyrights PergiKuliner.com - 2024'])[1]/following::a[1]</value>
      <webElementGuid>b9244bd3-de1a-464c-b828-9b5320107f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terserah aja deh!'])[1]/following::a[6]</value>
      <webElementGuid>a9a8ab0c-22e5-429f-a8da-b336d9687bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terserah aja deh!'])[2]/preceding::a[1]</value>
      <webElementGuid>81cf3de9-e442-4b21-9490-2e4d840a3de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/preceding::a[4]</value>
      <webElementGuid>693b4f97-ad4a-4103-8bd8-effb7bc8dc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PergiKuliner']/parent::*</value>
      <webElementGuid>10c80f76-8438-4605-8502-930f18ed4d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[10]</value>
      <webElementGuid>677f1a5d-3104-477f-919a-997ad40b0140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div/a</value>
      <webElementGuid>507b1a0a-6716-4f6a-9521-ca845994a7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'PergiKuliner Home' and @href = '/' and (text() = 'PergiKuliner' or . = 'PergiKuliner')]</value>
      <webElementGuid>deb7cbd6-6b8c-4213-9d9c-cb17d62d3528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
