<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PergiKuliner</name>
   <tag></tag>
   <elementGuidId>ac71e714-bc37-40b7-aaa3-dc1a08056cfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.navbar-brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerweb']/div/nav/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b55ef8fe-b217-4446-9dd7-d0e276786569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand</value>
      <webElementGuid>498da502-6d2d-4d6a-95a9-6a0eb883c867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PergiKuliner Home</value>
      <webElementGuid>b6bf09de-1155-4681-b874-ec8087431330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>ddfd90ec-7579-48a4-b46a-5148599330ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PergiKuliner</value>
      <webElementGuid>501c7630-ffae-4e8e-add7-72faba32e802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerweb&quot;)/div[@class=&quot;wrapper new-home&quot;]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;navbar-header&quot;]/div[@class=&quot;sm-scr-center-adj&quot;]/a[@class=&quot;navbar-brand&quot;]</value>
      <webElementGuid>e1e62418-8ac0-410a-b2c1-96f36283a32a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerweb']/div/nav/div/div/div/a</value>
      <webElementGuid>42ce9ee5-7625-460b-af01-e6b1ab8c3d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PergiKuliner')]</value>
      <webElementGuid>5e3a0ca9-c8e4-4efc-b2a5-f6369e0d26a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© copyrights PergiKuliner.com - 2024'])[1]/following::a[1]</value>
      <webElementGuid>1dc68a34-db78-42c0-9cbb-115c04e01b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terserah aja deh!'])[1]/following::a[6]</value>
      <webElementGuid>d4277862-dc2e-4584-ba4b-9de966718c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terserah aja deh!'])[2]/preceding::a[1]</value>
      <webElementGuid>93e4fcf1-9dca-4e84-be04-1229362ee29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/preceding::a[4]</value>
      <webElementGuid>083903cd-0338-4a0e-ab0d-9c6310e132a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PergiKuliner']/parent::*</value>
      <webElementGuid>066768f4-0b60-4e5d-b179-d1c1f314d2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[10]</value>
      <webElementGuid>1d3c043b-67ff-41f0-b332-00ffe3088bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div/a</value>
      <webElementGuid>e9054c88-ee9b-4786-8cf1-4cd3f60eba5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'PergiKuliner Home' and @href = '/' and (text() = 'PergiKuliner' or . = 'PergiKuliner')]</value>
      <webElementGuid>84cd59f6-2e89-444a-aa0c-73916e9aa555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
