<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PergiKuliner</name>
   <tag></tag>
   <elementGuidId>6f4b20c1-0a6c-4093-8874-d00a9a602ae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.navbar-brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerweb']/div/nav/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8c0ad73-d61f-493b-8813-5526d45fb0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand</value>
      <webElementGuid>b8c73d1f-ab81-45b3-ae78-943b8fb48362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PergiKuliner Home</value>
      <webElementGuid>2761b047-5054-4db2-9575-5d51a33628fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>c249d333-be52-415e-a09f-918daee4ec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PergiKuliner</value>
      <webElementGuid>37cad037-ff8b-4312-bec6-555530bf9076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerweb&quot;)/div[@class=&quot;wrapper new-home&quot;]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;navbar-header&quot;]/div[@class=&quot;sm-scr-center-adj&quot;]/a[@class=&quot;navbar-brand&quot;]</value>
      <webElementGuid>7c098fdc-0660-40ac-b99f-8a08505103e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerweb']/div/nav/div/div/div/a</value>
      <webElementGuid>e4953e28-982e-4dc3-88e7-b006621d2e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PergiKuliner')]</value>
      <webElementGuid>9e040127-1843-4443-a2ba-fe5439493db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© copyrights PergiKuliner.com - 2024'])[1]/following::a[1]</value>
      <webElementGuid>86ff6e85-97d3-400f-861b-e04bb61ee9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terserah aja deh!'])[1]/following::a[6]</value>
      <webElementGuid>5bb69c77-8028-4564-a8a3-c1356a65f575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terserah aja deh!'])[2]/preceding::a[1]</value>
      <webElementGuid>f097a765-0624-45d6-b104-a2c8b2db3dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/preceding::a[4]</value>
      <webElementGuid>67af635e-505c-4f2b-a08f-d05000dd2303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PergiKuliner']/parent::*</value>
      <webElementGuid>54f9eb73-78c9-4a82-ac2e-e74ec33e7a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[10]</value>
      <webElementGuid>b16eb371-0fed-40d5-a123-b4cbb0a789c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div/a</value>
      <webElementGuid>c55a8c76-5949-4bcc-ab01-0d0e0bf29797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'PergiKuliner Home' and @href = '/' and (text() = 'PergiKuliner' or . = 'PergiKuliner')]</value>
      <webElementGuid>4fda0b7b-692c-441a-9e11-55361ffd4f69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
