<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-signup</name>
   <tag></tag>
   <elementGuidId>1a9d1fb9-603a-4d3b-b98b-017105a1a35f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-sign-up > div.form-group > div.col-lg-12 > input[name=&quot;commit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='commit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8941cfbf-d620-43f9-9e63-fd048946b707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>89e09f32-80e3-4c2c-b004-33b1a4c6a515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commit</value>
      <webElementGuid>3f0468fb-fa76-4bee-b095-1d5a272ab8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Signup</value>
      <webElementGuid>39a65001-08ee-46fb-a065-08aee61d263d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn user-btn</value>
      <webElementGuid>0ea31915-cc38-4e7c-a766-d6f939b8da92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disable-with</name>
      <type>Main</type>
      <value>Proses..</value>
      <webElementGuid>b0a5ef5e-dd90-4724-bf36-6864232607b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-sign-up&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-lg-12&quot;]/input[@class=&quot;btn user-btn&quot;]</value>
      <webElementGuid>9f526d77-8b15-473f-a1b5-f7a3cd4f16a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='commit'])[2]</value>
      <webElementGuid>ac84c239-f498-4d02-91da-fdc80de296c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='modal-sign-up']/div[7]/div/input</value>
      <webElementGuid>ed95501f-99f6-4201-850c-e747fb2c44d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>e61d8ffc-2a52-4625-ad37-09fbed54c2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'commit']</value>
      <webElementGuid>18222e8b-3694-47a1-8cdc-47bab6461462</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
