<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpt_password_confirmation</name>
   <tag></tag>
   <elementGuidId>cf77d570-761d-4e3b-8784-3343b8ee1075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_password_confirmation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_password_confirmation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ef8b568-fa18-444e-8cf7-45c5aab89cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a09ddd98-4ec7-4a39-8262-98e1904618e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Konfirmasi Password</value>
      <webElementGuid>743ca797-34e2-4f15-8264-b268cec855d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>309f09e9-b32e-48b1-a77c-b3a88edc6a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[password_confirmation]</value>
      <webElementGuid>b3fc5a16-66bf-4391-94cc-5d60510c51bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_password_confirmation</value>
      <webElementGuid>5eda04b4-d2f3-4a5e-bd44-0805c5034ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_password_confirmation&quot;)</value>
      <webElementGuid>347d40d2-dd2c-4735-a386-0c10412fd32d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_password_confirmation']</value>
      <webElementGuid>8988b8d9-e666-4723-bb11-aa7a12bf3aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='modal-sign-up']/div[4]/div/input</value>
      <webElementGuid>71fc3c7f-297f-4cff-9e77-d44d9bb7d145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/form/div[4]/div/input</value>
      <webElementGuid>6ec243a5-34e7-43f4-88fa-4351e98bec98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Konfirmasi Password' and @type = 'password' and @name = 'user[password_confirmation]' and @id = 'user_password_confirmation']</value>
      <webElementGuid>65c009db-a497-4947-9b31-706e7ef97d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
