<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpt_checkbox</name>
   <tag></tag>
   <elementGuidId>8e9dd854-0ffe-4175-945a-dfa5b8d38584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_is_accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_is_accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fff1b42-25d0-428a-af4d-3924764776e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d5082fd1-a5f9-4e3e-925e-dda24e8ce315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf1cf11b-f7c2-4328-94ef-fe319504d38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[is_accept]</value>
      <webElementGuid>71bd9227-7f6f-498c-84ea-a7b720e50505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_is_accept</value>
      <webElementGuid>809689a2-5f30-4a33-b78d-6bccf10727d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_is_accept&quot;)</value>
      <webElementGuid>70a9406e-936f-4ef7-9883-cc97b2c1e3d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_is_accept']</value>
      <webElementGuid>90f7ee3f-bad5-4878-a38e-8766a9032c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='modal-sign-up']/div[6]/div/input[2]</value>
      <webElementGuid>8c895831-1b11-4bc5-b0f5-db04ef7cfa0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>657a4e66-f073-4a69-b724-32fadf4dd062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'user[is_accept]' and @id = 'user_is_accept']</value>
      <webElementGuid>e1efe8e7-4c9d-4c2c-8539-ad220067ac8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
