<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpt_username</name>
   <tag></tag>
   <elementGuidId>889b4aa4-aac2-44e0-98fc-07c4389df334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_user_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_user_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c136379-b09c-4a43-ae55-2072f7c9732f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c7205596-b140-4cc4-9c1b-ce98d9519a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>aa35829e-cc8f-45ae-97fb-00a43fb9bb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae2765de-5114-4eb7-916c-fd7eef9ffbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[user_name]</value>
      <webElementGuid>efd349f2-a4c5-45c5-b488-3115766b9954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_user_name</value>
      <webElementGuid>4a5d7560-ee8e-4968-8339-ba6f3c11e8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_user_name&quot;)</value>
      <webElementGuid>5ddef657-330c-4318-928e-dcfa2e6662d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_user_name']</value>
      <webElementGuid>71ebc91d-f931-4de5-a583-d33ad300d535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='modal-sign-up']/div/div/input</value>
      <webElementGuid>442b31c6-1c96-4f0e-bed8-81fffbe9a91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>feb492d4-399a-42b1-87b8-131ca8648f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Username' and @type = 'text' and @name = 'user[user_name]' and @id = 'user_user_name']</value>
      <webElementGuid>e3b3ad68-c8f9-4f06-b711-65e85b065566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
