<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inpt_email</name>
   <tag></tag>
   <elementGuidId>8a59f494-43a1-4231-b24b-b6938a27e460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signup_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signup_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44543940-b633-4b4e-b4d3-e69040bd3db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6816c293-0205-4774-8ab3-0888ef9bdf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alamat Email</value>
      <webElementGuid>78361e03-cb06-46a2-a9db-268151d9706c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup_email</value>
      <webElementGuid>52d868c2-4e8c-4ad0-af4a-96c38c5ae5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>18c47816-5c3f-4a9b-ba13-22cb64f6c1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[email]</value>
      <webElementGuid>db59421c-9ecd-4462-954e-cfa8941695c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_email&quot;)</value>
      <webElementGuid>6f9b2c3d-62d4-4287-9c33-157343891ec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signup_email']</value>
      <webElementGuid>b8844d7b-aca1-48c3-ba43-c4160e40f260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='modal-sign-up']/div[2]/div/input</value>
      <webElementGuid>bad629b3-b43e-4449-921a-d05c8b9cdbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/form/div[2]/div/input</value>
      <webElementGuid>186b5ce3-43a0-42f9-875d-72a2f26cf562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Alamat Email' and @id = 'signup_email' and @type = 'email' and @name = 'user[email]']</value>
      <webElementGuid>1b66eead-22e8-4db4-92c5-02fc6d23e601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
